project:
  type: book

book:
  title: "Søknad Merittert Utdanner UiO 2023"
  author: "Lex Nederbragt"
  date: today
  date-format: long
  language: nb
  chapters:
    - index.qmd
    - redegjoerelse.qmd
    - referanser.qmd
    - ped_mappe.qmd
    - cv_online.qmd

bibliography: pedagogisk_mappe.bib
csl: plos-computational-biology.csl
link-citations: true

format:
  html:
    theme: cosmo
    citations-hover: true
  docx:
    toc: false
    reference-doc: word_template_redegjoerelse.docx
#  pdf:
#    documentclass: scrreprt
#    toc: false



