# Introduksjon {.unnumbered}

::: {.content-visible when-format="docx"}

Todo liste for word versjonen

- [ ] fjern tittel dato, forfatter
- [ ] split up into redegjørelse.docx og pedagogisk_mappe.docx
- [ ] legg til antall ord på toppen, inkludert 'Utenom referanser'

```
cp _book/Redegjørelse-søknad-Merittert-Utdanner-UiO-2023.docx Redegjørelse_Lex_Nederbragt.docx
cp _book/Redegjørelse-søknad-Merittert-Utdanner-UiO-2023.docx Pedagogisk_mappe_Lex_Nederbragt.docx
```


HUSK ikke skriv ut som PDF, men 'Lagre som...' --> 'PDF'
:::

::: {.content-visible when-format="html"}

Dette er en web-versjon av søknaden jeg skrev for å bli Merittert Utdanner ved UiO i 2023.
[Søknaden ble innvilget](https://www.uio.no/om/aktuelt/aktuelle-saker/2023/ni-nye-meritterte-utdannere-ved-uio.html).

Søknaden består av:

* [Redegjørelse](redegjoerelse.qmd), der jeg viser hvordan jeg oppfyller SoTL-kriteriene
* [Pedagogisk mappe](ped_mappe.qmd), er en samling med dokumentasjon som støtter opp under redegjørelsen.
  Filene det referes til er ikke lagt ut her.
* [Utdanningsfaglig CV](cv_online.qmd)


Denne søknaden er skrevet som en Quarto bok.
Se kilden til disse sidene, skrevet i Quarto Markdown, [på GitHub](https://github.com/lexnederbragt/soeknad_merittering).
For å lære mer om Quarto, besøk <https://quarto.org/docs/books>.
:::

