# Pedagogisk mappe

<!-- TODO
* legg til 2017 og 2019 (?) versjonen av kursboken for å vise endring av rekkefølge
 -->

## BIO2120 {#sec-vl-bio2120}

* Kurstittel: **Evolusjonsbiologi**
* Emnesider: <https://www.uio.no/studier/emner/matnat/ibv/nedlagte-emner/BIO2120>

## Kurs og workshops 2009-2011

* Jeg organisert et unix kurs for kolleger i 2009
* Jeg organisert kurs i verktøyet awk, plotting i R og PERL programmering for kolleger i 2010
* med kolleger fra Norsk Sekvenseringsenter organiserte vi et kurs 
  ["High Through-put Sequencing: technology basics, applications and bioinformatic analysis"](https://www.sequencing.uio.no/events/2011/nsc_course_2011.html)
  i 2011
<!--- PDF av denne nettsiden: "/Users/alexajo/current/teaching/older/2011/NSC HTS course Oct 2011/NSC course: High Through-put Sequencing: technology basics, applications and bioinformatic analysis .pdf" --->


## Software Carpentry, Data Carpentry, The Carpentries, Carpentry@UiO  {#sec-vl-carpentry}

* I 2018 ble [The Carpentries](https://carpentries.org) dannet av en sammenslåing av 
  * [Software Carpentry](http://software-carpentry.org/)
  * [Data Carpentry](http://www.datacarpentry.org/)
* Jeg er en sertifisert [instruktør](https://carpentries.org/instructors/) og [instruktør trener](https://carpentries.org/trainers/)
  * Fil: `SoftwareCarpentry_Instructor_Certificate.pdf`
  * Fil: `DataCarpentry_Instructor_Certificate.pdf`
  * Fil: `Carpentries_Instructor_Trainer_Certificate.pdf`

* Jeg har bidratt til undervisningsmaterial til The Carpentries
  * [The Carpentries Instructor Training](https://carpentries.github.io/instructor-training/index.html) [@erinalisonbecker2019Carpentries]
  * Software Carpentry: [The Unix Shell](http://swcarpentry.github.io/shell-novice) [@aldazabalmensa2017Software]
  * Software Carpentry: [Programming with Python](http://swcarpentry.github.io/python-novice-inflammation) [@achterberg2017Software]
  * Software Carpentry: [Version Control with Git](http://swcarpentry.github.io/git-novice) [@koziar2023Software]
  * Software Carpentry: [Automation and Make](http://swcarpentry.github.io/make-novice) [@allen2017Software]
  * Data Carpentry: [Data Wrangling and Processing for Genomics](https://datacarpentry.org/wrangling-genomics/) [@wilson2017Data]

* Jeg var også medlem av The Carpentries [Executive Council](https://carpentries.org/governance/),
  som kan sees på som organisajsonens styret (2018-2021)
* Carpentry@UiO
  * Sammen med Karin Lagesen og Realfagsbiblioteket etablerte vi i 2014 Carpentry@UiO
  * UiO er siden 2017 [medlemsorganisasjon](https://carpentries.org/members/) av The Carpentries
  * Webside til [Carpentry@UiO](https://uio-carpentry.github.io),
    bl.a. med oversikt over [tidligere workshops](https://uio-carpentry.github.io/workshops/#past-workshops)
  * Websidene fra Universitetsbiblioteket:
    * [carpentry.uio.no](https://www.uio.no/carpentry)
    * [oversikt over workshops](https://www.ub.uio.no/english/courses-events/courses/other/Carpentry/)
  * Jeg leder [styret for Carpentry@UiO](https://uio-carpentry.github.io/about/members/)
  
* Foredrag om Carpentry@UiO mm
  * På et miniseminar "Open Data Skills" ved UiO i 2016 holdt jeg foredraget
    "The Carpentry effort at the University of Oslo"
  * På NARMA (Norsk nettverk for Forskningsadministrasjon) sin Vårkonferanse 2017
    holdt jeg et foredag om
    "Software Carpentry og Data Carpentry: opplæring i bruk og deling av forskningsdata – for forskere, av forskere, ved UiO"
  * På 2017 Nordic eInfrastructure Collaboration conference holdt jeg foredraget
    "Teaching Researchers Basic Skills for Computational Research: the Software Carpentry Model"
  * På konferansen CarpentryConnect i Manchester i 2019 presenterte jeg en keynote lecture 
    med tittel "Learning from the Carpentries". 
    Se [opptaket](https://www.youtube.com/watch?v=-VMItG68LcM).
  * På online konferansen 'CarpentryCon online 2022' presenterte jeg
    "Carpentry@UiO: Workshops for basic skills in programming and datamanagement at The University of Oslo (UiO)".
    Se [opptaket](https://www.youtube.com/watch?v=INU4GdFPL9s&t=10m00s) (fra tidspunktet 10:00)


* Software Carpentry workshops jeg har bidratt til
  * Universitetet i Oslo: 2012, 2013, 2015 - 2023
  * Netherlands eScience Centre: 2017
  * Universitet i Bergen: 2014
  * Science for Life Laboratory, Stockholm, Sverige: 2014
  * Online (ved UiO): 2020, 2021

* Instruktør trening workshops jeg har undervist for
  * Universitetet i Oslo: 2016, 2018
  * University of California, Davis, 2017
  * Online for the Carpentries: 2016-2019


## INF-BIO5120/9120 {#sec-vl-infbio}

* Kurstittel: **High Throughput Sequencing technologies and bioinformatics analysis**
* Emnesider: <https://www.uio.no/studier/emner/matnat/ifi/INF-BIO5120/index-eng.html>
* Kurssidene med alt kursmaterialet for 2016: <http://inf-biox121.readthedocs.org/en/2016>
* På FEBS-IUBMB Workshop on education in molecular life science i 2015 hadde jeg en poster
  med tittel "Active learning strategies for bioinformatics teaching"
    * Fil: `150918_poster_workshop-molecular-life-sciences_Nederbragt.pdf`

## BIOS1100 {#sec-vl-bios1100}

* Kurstittel: **Innføring i beregningsmodeller for biovitenskap**
* Emnesider: <https://www.uio.no/studier/emner/matnat/ibv/BIOS1100/>
* [Semestersidene 2017](https://www.uio.no/studier/emner/matnat/ibv/BIOS1100/h17/ressurser/hovedside.md)
* [Canvas sidene 2018](https://uio.instructure.com/courses/5848)
* Pensumbok "Introduction to Analysis and Modeling in Biology with Python",
  ble skrevet, med støtte av CCSE (Center for Computing in Science Education)
  av fire PhD studenter som en del av sin pliktarbeid,
  under ledelese av meg.
  Jeg jobber for tiden med å ferdigstille boken slik at den kan publisere.
  Den siste versjon (august 2022) er vedlagt som fil: `intro_analysis_modeling_biology_python_220810.pdf`
* For å lette informasjonsoverføring til dem har jeg laget en omfattende nettside med
  [dokumentasjon til gruppelærere](https://pages.github.uio.no/alexajo/bios1100-assistants/start.html)
  (krever login med UiO brukernavn og passord)
* Jeg har skrevet noen blogposter om BIOS1100: <http://lexnederbragt.com/bios1100>
* Sammen med undervisere involvert i arbeidet med integrering 
  av beregningsperspektivet i bachelor utdanningen ('CSE@IBV')
  skrev vi rapporten "Computing in Science Education (CSE) på IBV: status og veien videre".
  * Fil: `Status CSE på IBV februar 2020 og veien videre.pdf`

## Foredrag om BIOS1100 {#sec-vl-deling}
<!-- Tone: Kollegial holdning og praksis handler også om å dele kunnskap med andre
i form av foredrag – har du hold toe på UnderVerk? Real U? MNT konferansen? -->

* Jeg har presentert arbeidet med BIOS1100 i Studieutvalget ved MN-fakultetet (STUT), ved flere anledninger.
* På CCSE sitt juleseminar i 2017 presenterte jeg "BIOS1100 - Innføring i beregningsmodeller for biovitenskap"
* På et et Undervisningsseminar for NT-fak, Univ. i Tromsø i 2018 holdt jeg et innlegg om
  "Programmering og modellering i biovitenskapsutdanning"
* Da MN fakultetet ved UiO fik besøk av MN fakultetet ved UiB i 2018 for å diskutere
  "Utdanningsutvikling med fokus på digitale ferdigheter og generisk kompetanse"
  presenterte jeg "BIOS1100 Innføring i beregningsmodeller for biovitenskap – erfaringer og videre utvikling"
* Jeg presenterte i 2020 for en arbeidsgruppe fra Circle-U
  som skulle samle erfaringer rundt generiske/overførbare ferdigheter i utdanningen
  "Computing in Bioscience Education"
* På en instituttsamling ved Farmasøytiskk Institutt i 2022,
  under Temaet "Beregningsvitenskap og digital kompetanse i utdanning",
  presenterte jeg "Implementering av beregninger i studieprogrammet Biovitenskap
  med noen refleksjoner rundt farmasiutdanningen"


  
## Samkoding {#sec-vl-samkoding}

* Jeg har laget to korte filmer for å vise hvordan å (ikke) gjøre samkoding.
  Disse filmene blir brukt i [opplæring av instruktører for the Carpentries](https://carpentries.github.io/instructor-training/17-live.html#compare-and-contrast):
  * [Eksempel 1](https://youtu.be/bXxBeNkKmJE)
  * [Eksempel 2](https://youtu.be/SkPmwe_WjeY)

* Jeg har skrevet en fagfellevurdert artikkel om teknikken @nederbragt2020Ten.
  * **A. Nederbragt, R. M. Harris, A. P. Hill and G. Wilson** (2020). "Ten quick tips for teaching with participatory live coding", *PLOS Computational Biology*, 16(9), pp. e1008090, [doi: 10.1371/journal.pcbi.1008090](https://dx.doi.org/10.1371/journal.pcbi.1008090)


## Jupyter notebooks og JupyterHub {#sec-vl-jupyter}

  * JupyterHub: en skytjeneste UiO har satt opp
    som studentene kan logge seg inn på uten behov for installasjon på egen maskin.
    Denne ble satt opp i 2017 bl.a. for BIOS1100, og brukes nå av mange kurs ved UiO:
    <https://jupyterhub.uio.no>
  * [Dokumentasjon for studenter](https://www.uio.no/tjenester/it/forskning/beregning/jupyter/)
  * [Dokumentasjon for undervisere](https://www.uio.no/english/services/it/research/hpc/jupyter-notebook/for-teachers/index.html)
  * I 2021 holdt jeg et foredrag om "Using Jupyter for teaching programming to bachelor students in Bioscience" 
    for Senter for Fremragende Utdanning ved UiO iEarth
    * Websiden: <https://www.iearth.no/resource/iearth-digital-learning-forums-from-2021> (skroll ned til 03.06.2021)
    * Opptak av foredraget: <https://vimeo.com/558878621>
* I 2019 fikk vi sammen med kjemisk institutt og USIT 
  innvilget prosjektet "Integrasjon av Jupyter og Canvas for digital vurdering",
  som skal gjøre det sømløst og kombinere disse to plattformer
  * [Utlysning av prosjektmidler for digital vurdering](https://www.uio.no/link/arrangementer/2019/digitalvurdering/prosjektmidlerdigitalvurdering.pdf)
  * Søknad: fil: `Jupyter-Canvas-LINK_2019_signert.pdf`
  * [Prosjektsiden](https://www.usit.uio.no/om/organisasjon/itf/aktiviteter/prosjekter/jupyter-canvas) (krever login med UiO brukernavn og passord)

<!---
 ## Formativ vurdering med Peer Instruction {#sec-vl-formvurd}

* Siden med [alle flervalgsspørsmål utviklet for BIOS1100](https://www.uio.no/studier/emner/matnat/ibv/BIOS1100/h22/alle-flervalgssporsmal-i-bios1100-h22.html) 
--->

## Emneevalueringer {#sec-vl-emneeval}

* BIOS1100 (2017-)
  * Fil: `Sluttrapport BIOS1100 Hoesten 2017.pdf`
  * Fil: `Sluttrapport BIOS1100 Hoesten 2018.pdf`
  * Fil: `Sluttrapport BIOS1100 Hoesten 2019.pdf`
  * Fil: `Sluttrapport BIOS1100 Hoesten 2020.pdf`
  * Fil: `Sluttrapport BIOS1100 Hoesten 2021.pdf`
  * Fil: `Sluttrapport BIOS1100 Hoesten 2022.pdf`


## Forskning på egen undervisning  {#sec-vl-forskning}

* Konferansebidrag
  * MNT konferansen mars 2019: **Gregers, T.F., and Nederbragt, Lex** (2019). Lektorstudenter utvikler unik kompetanse og bidrar til økt kvalitet på begynneremner gjennom en undervisningsrettet master. *Nordic Journal of STEM education* 3, 23–27, <https://doi.org/10.5324/njsteme.v3i1.2992>. Tilgjengelig som fil: `Gregers and Nederbragt, Lex - 2019 - Lektorstudenter utvikler unik kompetanse og bidrar.pdf`
  * MNT konferansen mars 2021: **J.E.Eliassen, M.V.Bøe, L.Nederbragt, M.M.Berg, og T.F.Gregers** (2021). Motivasjon for beregningsorientert biologi og sammenhengen med matematikk R2 fra videregående opplæring. *Nordic Journal of STEM education*, *in press*. Tilgjengelig som fil: `Eliassen_etal_2021_Motivasjon for beregningsorientert biologi.pdf`

* Masterstudent June Edvarda Eliassen (2020)
  * Tittel: Biologistudenters motivasjon for beregningsorientert biologi etter innføring av krav om full fordypning i realfaglig matematikk
  * Lenke til oppgaven: <http://urn.nb.no/URN:NBN:no-82918>
  * Fil: `Masteroppgave_Eliassen.pdf`

* Masterstudent Sofie Rudberg (2020)
  * Tittel: Relevansen av kompetansen fra matematikk R2 i beregningsorientert biologi
  * Lenke til oppgaven: <http://urn.nb.no/URN:NBN:no-82936>
  * Fil: `Masteroppgave_Rudberg.pdf`

* Masterstudent Marthe Mjøen Berg (2019)
  * Tittel: Studentar si interesse og meistringsforventning for programmering og modellering i biologi
  * Lenke til oppgaven: <http://urn.nb.no/URN:NBN:no-73633>
  * Fil: `Masteroppgave_Berg.pdf`

* Masterstudent Lars Erik Håland (2019)
  * Tittel: Studenters arbeid med programmering i biovitenskapelige problemstillinger. En kvalitativ studie av biologistudenters arbeid med Python
  * Lenke til oppgaven: <http://urn.nb.no/URN:NBN:no-73632>
  * Fil: `Masteroppgave_Håland.pdf`

## UnderVerk ved Institutt for Biovitenskap {#sec-vl-underverk}

* [IBV side om UnderVerk](https://www.uio.no/for-ansatte/enhetssider/mn/ibv/underverk)
  krever innlogging med UiO brukernavn og passord
* [KURT side om UnderVerk](https://www.mn.uio.no/kurt/undervisningsutvikling/underverk))
* teamet består av Tone Gregers, Hans-Petter Hersleth, Pernille Bronken Eidesen og meg selv
* Tone Gregers fikk i 2019 støtte fra MatNat fakultetets studiekvalitetsmidler 
  for å starte UnderVerk
* Noen av temaene for UnderVerk samlingene har vært
  - Hvordan å skrive LæringsUtbytte Beskrivelser ('LUB'er)
  - Læringsmål og baklengsdesign
  - Praktisk implementasjon av pedagogisk teori i undervisningsplanlegging
  - Studentaktive læringsformer
  - Bruk av digitale verktøy
  - Digital undervisning under pandemien
  - Vurderingsformer
  - Fusk
  - Universell Utforming

Under korona pandemien vår 2020 organiserte Underverk et ukentlig treff
i Zoom for erfaringsutveksling.

Mitt bidrag har vært å hjelpe med planlegging og gjennomføring, samt
bidra konkret til noen av workshopen:

- Teorien om Kognitiv Last (oktober 2019)
- Bruk av Zoom for digital undervisning (mars 2020)
- Digital hjemmeeksamen i BIOS1100 (november 2020)
- Universell Utforming

* [Læringsutbyttebeskrivelse for BIOS-IN5410](https://www.uio.no/studier/emner/matnat/ibv/BIOS-IN5410/#learning_outcomes)


<!-- TO DO: legge ved rapportene Tone skrev? -->
<!-- TODO: legge ved PDF av mine slides for UnderVerk -->

## Læringsassistenter og LA-seminaret {#sec-vl-la}

En læringsassistent er en pedagogisk trent bachelor- eller masterstudent,
eller ph.d.-kandidat, som legger til rette for studentdiskusjon,
problemløsning og gruppearbeid som del av undervisningen i et emne.

* MatNat tilbyr [opplæring til gruppelærene](https://www.mn.uio.no/kurt/utdanningsutvikling/gruppeundervisning-/Læringsassistenter%20/.)
  slik at de blir læringsassistenter gjennom [LA-seminaret](https://www.mn.uio.no/kurt/utdanningsutvikling/gruppeundervisning-/la-seminaret-.html)
* CCSE har en [nyhetssak om LA seminaret](https://www.mn.uio.no/ccse/english/about/news-and-events/news/learning-assistant-seminars.html)

## MNPED9000 {#sec-vl-mnped0000}

* Kurstittel: **Teaching in STEM**
* Emnesider: <https://www.uio.no/studier/emner/matnat/mn/MNPED9000>

## Prosjekt Digitale Læringsmiljø 2030 {#sec-vl-dlm2030}
* [Prosjekts webside](https://www.uio.no/for-ansatte/arbeidsstotte/prosjekter/nestegenerasjons-digitalt-laringsmiljo/index.html)
* [Sluttrapport](https://www.uio.no/for-ansatte/arbeidsstotte/prosjekter/nestegenerasjons-digitalt-laringsmiljo/sluttrapport-prosjekt-digitalt-leringsmiljo-2030.pdf)
* Fil: `Sluttrapport prosjekt Digitalt læringsmiljø 2030.pdf`

## Arbeidsgruppen for gjennomgang av ferdighetstrening i biovitenskapsprogrammet {#sec-vl-ag-ibv}
* Fil: `Anbefalinger fra arbeidsgruppe for ferdighetstrening.pdf`

## Annet

* Foredrag
  * **BIOS1100: Innføring i beregningsmodeller biovitenskap – erfaringer og evaluering**, Real utdanning – fagdag for utdanning ved MN fakultetet, 2018
  * **Programmering og modellering i biovitenskapsutdanning**, Undervisningsseminar om beregningsorientert realfagsundervisning for NT-fakultet, Universitet i Tromsø/Norges Arktiske Universitet, 2018 (invitert)

* Mediaoppmerksomhet mm
  * besøk av daværende kunnskapsministeren til UiO, inkludert undervisningen i BIOS1100
    * artikkel i [Uniforum](https://www.uniforum.uio.no/nyheter/2017/10/henrik-asheim-blei-begreistra-for-forsking-og-unde.html)
    * artikkel på "IBV sine websider": <https://www.mn.uio.no/ibv/om/aktuelt/aktuelle-saker/2017/kunnskapsministeren-imponert-over-bios1100-og-igem.html>
  * ['Programmerings- revolusjonen'](https://issuu.com/nokut/docs/sfu_magasinet_02.18_72dpi_enkeltsid); artikkel i SFU-magasinet 2018/2, side 25
  * Det ble publisert en artikkel på MatNat sine sider om [hvordan det er å studere biovitenskap](https://www.uio.no/studier/program/biovitenskap/studiemiljo/hvordan-er-det-a-studere-biovitenskap.html) som spesifikt nevner programmeringsundervisning som en styrke



## Vedlegg for Utdanningsfaglig CV {#sec-vl-cv}

### Universitetspedagogisk kompetanse

* *Felles innføringsdel* for Universitetspedagogisk Basiskompetanse i 2019
  * Kursbevis: Fil: `Kursbevis_universitetspedagogisk_basiskompetanse.pdf`
  * Utviklingsnotat: Fil: `Utviklingsnotat_Fellesdelen_2019.pdf`

* moduler tatt i tillegg til Fellesdelen:
  * Forskningsveiledning (2014)
    * Utviklingsarbeid: Fil: `Utviklingsarbeid_Forskningsveiledning_2014.pdf`
  * Forelesning og undervisning - det dramaturgiske aspekt (2015)
  * Pedagogisk mappe (2020)
  * Læring og undervisning med universell utforming (2022)
    * Innlevering: Fil: `Assignment_UU_2022.pdf`

* *Felles innføringsdel* i 2014 som 20% 1. amanuensis II
  * Utviklingsarbeid: Fil: `Utviklingsarbeid_Fellesdelen_2014.pdf`

### Lederroller

* CCSE
  * Jeg er en del av [ledergruppen](https://www.mn.uio.no/ccse/english/about/organization/leader-group/)
  * Bidrag til [CCSE sine årsrapporter](https://www.mn.uio.no/ccse/english/about/reports)
