# Redegjørelse {.unnumbered}

Det som kjennetegner meg som underviser

* sterkt overbevist om at undervisere bør bruke resultater
  fra vitenskapelig forskning på læring og utdanning
  når man planlegger og utvikler sin undervisning
* Studentenes læring står sentralt (?)
* forsker i bunn, søker hele tiden ny kunnskap for å skape god undervisning
  og utvikler deg selv som underviser
* har en driv til å dele
* pioner i det digitale (?)
* endringsagent i eget fag og miljø, initiativtaker, ildsjel, modernisere biofaget
	- samarbeid med mange som også er iteressert i programmeing
	- samtidig som jeg prøver å bevege egen organisasjon
* fokus på å undervise programmering til personer i fagfelt
  der dette tydeligere ikke har vært en naturlig del av opplæringen
* ønsker pedagogisk opplæring for nye undervisere
* viktigheten av å inkludere beregninger/programmeing i (tidlig)utdanning

Hva er motivasjonen min? Hva gjør at jeg vil stå i det? Hva er det som driver meg?

Hvordan forstår jeg studentenes læring?

- studenten må aktivt gå inn å bruke stoffet, helst diskutere med andre
- rollen til underviseren er å legge til rette for at dtusentene kan lære
- studentene må ha mulighet til å opplevre mestring
  (husk at mestringsfølelse kom først opp i emneevalueringen i 2020?)
- motivasjon, valg av materialer, autentiske problemstillinger
- kognitiv belastning

------

## En klar utvikling over tid med økende fokus på studentenes læring

Min første erfaring som underviser var som gruppelærer for et kurs i zoologi.
Jeg følte at jeg lærte en god del mer av å undervise faget, enn når jeg tok faget selv:
mens studentene så ett tverrsnitt av en kattenyre hver,
så jeg mange flere når studenter ba meg om hjelp.

Mine første forelesninger i kurset BIO2120 Evolusjonsbiologi, 
([ped.mappe @sec-vl-bio2120]) var standard 2x45 minutter.
Det var sikkert bra men hadde ingen studentaktivisering.
Jeg var nok mest opptatt av 'det jeg gjør som underviser'
og det å formilde kunnskap på en best mulig måte
- stadiet 1 og 2 i Kugels faser av utvikling av undervisere
[@kugel1993professors, se også @biggs2012What].

Da jeg som postdokter måtte lære meg å bruke kommandolinje-baserte verktøy,
programmering og supercomputere,
begynte jeg med en gang å utvikle og holde korte kurs og workshops for kolleger
i bruk disse verktøyene programmering.
Jeg oppdaget at jeg, når jeg lærer noe nyttig, ønsker å dele den nye kunnskapen
med andre som også kunne dra nytte av det.

Deretter ble jeg kjent med The Carpentries, en internasjonal
organisasjon av frivillige som organiserer workshops om verktøy
for forskere som bruker beregninger og programmering i sin forskning
('research computing') ([ped.mappe @sec-vl-carpentry]).
Etter å ha fått dem til å holde en av deres workshops på UiO
ble jeg vervet til å bli instruktør for organisasjonen.
Jeg gikk gjennom deres instruktørtrening,
som er forankret i pedagogisk forskning om læring:
mentale modeller, kognitiv belastningsteori, formativ versus summativ vurdering.

Jeg så at det ville være nyttig for flere forskere ved UiO kunne delta på Carpentries' workshops.
Jeg ønsket dermed å etablere en lokal avdeling av The Carpentries.
Sammen med en kollega fikk vi til et samarbeid med Realfagsbiblioteket,
og i 2016 etablerte vi Carpentry@UiO.
Carpentry@UiO har organisert mer enn ett hundre workshops
med deltakere fra alle fakulteter, universitetsbibliotek og IT-avdelingen
og UiO har flere titals personer utdannet som instruktør for organisasjonen
([ped.mappe @sec-vl-carpentry]).
Denne måten å organisere en slags etterutdanning på dugnadsbasis på
fungerer veldig bra,
mest fordi det knytter mennesker sammen på tvers som har samme behov,
og samme interesse i undervisning av disse metodene
på en pedagogisk gjennomtenkt måte.
Carpentry@UiO har bidratt til at mer enn ett tusen ansatte på UiO
har fått opplæring i verktøy som er umiddelbart relevant for deres arbeid.
Deres forankring i pedagogikk har inspirert mange.

Det å bli en del av dette praksisfellesskap,
('community of practice' @li2009Evolution) har betydd mye for meg.
Jeg fant likesinnede personer med lidenskap for undervisning 
av moderne forskningsteknikker som mange forskere trengte i sitt arbeid.
Å bli instruktør, og senere instruktørtrener,
for The Carpentries endret mitt syn på undervisningen totalt.
Det ble mitt første møte med pedagogikk.
Dette gjorde meg bevisst på viktigheten av motivasjon for læring,
det å begrense kognitiv last, formativ vurdering og
studentaktive læringsformer som hands-on læring.
Jeg flyttet meg også over til stadiet 3 i Kugels faser @kugel1993professors,
med fokus på den som jeg underviser til, heller enn på meg selv eller temaet,
Deltakere skulle kunne bruke det de fikk undervist med en gang etterpå.
Jeg også oppdaget at utdanning er en egen vitenskap,
og ble overbevist om at vi bør ta resultatene av den vitenskapen på alvor
når vi utvikler kurs.
Akkurat som tidligere forskning informerer oss når vi utvikler vår egen forskning,
bør pedagogisk forskning informere oss når vi utvikler vår egen undervisning.
Dette har guidet mine tanker rundt undervisningsdesign fra den tiden av.

I 2012 fikk jeg min første erfaring som kursansvarlig (emneansvarlig)
med INF-BIO5121/9121 ([ped.mappe @sec-vl-infbio]).
Dette lærte meg mye om hvordan undervisning foregår på et universitet, 
faser i et emne (forberedelse, gjennomføring, eksamen, klage),
og viktigheten av emneevaluering.

<!-- si litt om eksamen? Andre innovative und. formen? HPC serveren? -->

Min erfaring med å undervise programmering til forskere
som ikke har hatt det som en del av sin utdanning
bidro til at jeg i 2017 ble spurt å utvikle et nytt emne som emneansvarlig:
BIOS1100 - Innføring i beregningsmodeller for biovitenskap,
et obligatorisk førstesemesterkurs i studieprogrammet Biovitenskap.
Emnet skulle gi biologistudenter beregningskompetanse
som en del av fakultetets satsning på ‘Computing in Science Education’ (CSE)
([ped.mappe @sec-vl-bios1100]). 
Dette var en fantastisk måte å bidra til å modernisere biovitenskapsutdanningen.
Jeg hadde selv som forsker vært gjennom denne moderniseringen,
og det å kunne lære nye studenter disse nye 
forskningsnære arbeidsmetoder passet veldig godt
for en person som drives av å dele nyttig kunnskap med andre.

For å designe dette kurset ønsket jeg å ta utgangspunkt i
relevant pedagogisk teori og litteratur.
Jeg valgte å se på forksning om det å lære programmering,
og endte fort opp med å fokusere på
teorien om kognitiv belastning @sweller2019Cognitive.

Kognitiv belastningsteori er opptatt med hvordan belastning av arbeidsminne
kan optimeres for å fremme læring @sweller2019Cognitive
og er relevant for programmeringsundervisning @caspersen2007Instructional.
Overbelastning av arbeidsminnet hemmer effektiv overføring av ny kunnskap til langtidsminnet,
som er nødvendig for læring.
Denne teorien har vært påvirket min utdanningspraksis
når det gjelder valg av undervisningsmetoder og digitale verktøy.

Fra forskningen lærte jeg at å lære å programmere anses generelt som vanskelig
[@jenkins2002difficulty; @robins2003Learning; @bennedsen2007Failure; @guzdial2015LearnerCentered]:
det er mye å ha i hodet samtidig, syntaks, problemetløsningsstrategier, 
og den faglige konteksten.
Det oppstår fort bugs som kan være vansklig å finne og løse.
Min utfordring var nå å undervise programmering for studenter 
som (ofte) ikke har valgt biologi, som tradisjonelt er sett på som det 'myke realfaget'
for å lære akkurat det.
I tillegg skulle de lære det i et begrepstungt fag, med mange prosesser å forholde seg til.
Når disse to gingene skulle læres samtidig
er det fare for at den kognitive belastningen blir for høy.

Jeg bestemte meg å ta utgangspunkt i veiledet instruksjon ("Guided instruction") @fisher2013Better,
som bidrag til å begrense studentenes kognitive belastning.
Veiledet instruksjon er en undervisningsmetode
hvor instruktøren gir eksplisitt veiledning og støtte til studentene
gjennom hele læringsprosessen, heller enn å be studentene å finne ut konsepter selv @kirschner2006Why.

Noe om at jeg jobber med å senke KB gjennom 
i)samkoding,
ii) formativ vurdering med peer instruction
?

I praksis betyr dette for eksempel at jeg bruker noe som heter samkoding,
eller 'Participatory Live Coding':
en aktiv læringsteknikk der en underviser skriver kode og programmerer
sammen med studentene [se også min publikasjon om dette @nederbragt2020Ten].
([ped.mappe @sec-vl-samkoding]).
Dette er en form for veiledet instruksjon
som guider studentene gjennom å lære elementær programmeringsteknikker.

Teknikken, som jeg har lært av The Carpentries
der det er et sentralt element i deres workshops,
er ment å senke terskelen for å komme i gang med programmeringen.
I BIOS1100 brukes samkoding for å undervise elementære kunnskap i Python
gjennom hele kurset i samkodingsgruppene ledet av gruppelærere,
som får opplæring i teknikken
og bruker en samodingsoppskrift som jeg har utviklet.
Det lille som er av forskning på live-koding i undervisningen viser at
teknikken er like bra som, om ikke bedre enn å bruke statiske kodeeksempler @raj2018Role @raj2020Livecoding
og er derfor en anbefalt tilnærming for undervisning i programmering [@brown2018Ten; @wright2020why].

Selv om jeg visste at samkoding kunne være nyttig i BIOS1100
trodde jeg først ikke at det var mulig å skalere opp samkoding til 200 studenter.
Et av målene med samkodingen er at alle studenter følger med,
og at de skal kunne få hjelp når de sitter fast slik at de ikke faller av underveis.
I en stor gruppe kan det føre til at en student som har et problem
holder opp undervisningen for hele gruppen.

Jeg overså at jeg dermed stolte for mye på selvstendig læring av programmeringen
(‘minimal guidance’ @clark2012Putting).
Dette førte til at, første gang kurset ble undervist,
mange studenter meldte til studieseksjonen at de
var i ferd med å falle av fordi de ikke klarte å lære seg programmeringen.
De følte at de ikke kunne mestre dette sentrale elementet i kurset.
Dette kom som et sjokk over meg, og jeg ble nokså nedfor
at all arbeidet jeg hadde lagt inn i kurset føltes til ingen nytte
- studentene lærte ikke stoffet!

Jeg bestemte meg da å ta grep og bytte ut den planlagte undervisningen
for de tre siste ukene med et tilbudt til studentene som trengte det med økter med samkoding. 
Tilbakemeldinger fra studenter på dette var overveldende positivt,
og en god del fortalte meg og studieseksjonen etterpå
at de nå følte at de hadde forstått det vesentlige med programmeringen.

Jeg implementerte deretter denne teknikken som en fast del av undervisningen.
Studentene melder tilbake at de opplever mye læringsutbytte av den,
og det første året sa en gruppelærer at 'grunnmuren i programmering sitter mye bedre'.
Denne episoden lærte meg viktigheten av å få tilbakemeldinger fra studentene,
eventuelt via studieseksjonen, underveis i kurset.
Det er alt for lett å anta at et gjennomtenkt undervisningsopplegg
fungerer i praksis.
Jeg er fortsatt stolt over at jeg klarte å snu undervisningen for å
'redde' studentene som var i ferd med å falle av.
I tillegg ble jeg enda mer overbevist om merverdien av samkoding som undervisningsteknikk.

<!--- Andre eksempler på grep som tar utgangspunkt i kognitiv belastning
er 

1) endringer jeg gjorde i rekkefølge av undervisning av sentrale Python elementer.
Konkret endret undervises while løkekr nå før for løkker,
og undervises Numpy arrays mye mindre tett opp på vanlige lister i Python. 
--->

<!-- Løsningen var å skrive om kursboken, som hjalp mye med å redusere forvirringen etterpå. -->
<!-- Tone: Har du vært involvert I å skrive boken?
HVordan har dette påvirket din utvikling som underviser i beregningsorientert biologi?
Hvordan skrev dere i såfall om boken? Hva ble viktig å endre? -->

I tillegg til valg av undervisningsteknikk
har jeg også tatt utgangspunkt i kognitiv belastning
for valg av programmeringsomgivelse.
Jeg valgte Jupyter notebooks fordi dette brukergrensesnittet
kombinerer tekst og kode, og lar brukeren
både skrive og kjøre kode på samme sted.
Notebooks blir også brukt av forskere verden over.
Det er nokså intuitivt å bruke, og infrastrukturen UiO har satt opp
gjør det enkelt å gi alle studenter tilgang.
Dette minsker dermed den kognitive belastningen
som et mer komplekst brukergrensesnitt ville medført.
Notebooks blir gjort tilgjengelig gjennom UiO sin JupyterHub,
en skytjeneste som studentene kan logge seg inn på uten behov
for installasjon på egen maskin.
Denne ble satt opp bl.a. for BIOS1100, og brukes nå av mange kurs ved UiO
([ped.mappe @sec-vl-jupyter]).
Studentene liker bruken av notebooks og bekrefter at det er lett å komme i gang med.
I 2019 søkte fikk vi sammen med kjemisk institutt og USIT
innvolget prosjektet "Integrasjon av Jupyter og Canvas for digital vurdering",
som skal gjøre det sømløst og kombinere disse to plattformer
for innleveringsoppgaver ([ped.mappe @sec-vl-jupyter]).

En utfordring vi hadde var at det digitale eksamensystsmet Inspera ikke 
tilbyr mulighet for å bruke notebooks som innleveringsform,
eller teste kode som studentene skrev under eksamen.
Men, i dialog med kollegaer som underviser
begynnerprogrammering for Informatikk studenter
valgte jeg og aksepterer dette.
Argumentasjonen var at studentene ved å ikke kunne kljøre kode
ikke skulle bruke mye tid på fikse syntaksfeil, 
men heller kunne fokusere på å ferdigstille programmet sitt.
Men tilbakemeldinger fra studentene,
og en økende bevissthet om baklengs design
og meningsfylt samsvar (constructive alignment, @biggs2012What)
som jeg fikk i denne perioden, har endret synet mitt.

Derfor tok jeg initiativ og ba i 2019 
om en egen eksamensinstans for JupyterHub i Silureveien,
som kunne brukes av studentene å skrive besvarelser som notebooks,
og laste disse opp til Inspera.
Dette ble mulig og har blitt brukt siden, også av et annet kurs.
Jeg så på dette som et viktig grep for å få økt meningsfylt samsvar
mellom undervisningen og eksamensform.
Før var det et stort gap siden studentene måtte skrive eksamensbesvarelsene
på en fullstendig annerledes måte enn som de hadde jobbet under kurset.
Nå var dette blitt likt.
Dette har bidratt til å redusere eksamensstresset,
har gitt studentene mye bedre forutsetninger for eksamen,
er en måte som i mye større grad lar studentene demonstrere hva de har lært.
Mitt håp er at det også har bidratt til mer læring @biggs2012What.

Et annet viktig hjelpemiddel som jeg har tatt i bruk for 
å undersøke studentenes læring er formativ vurdering
kombinert med Peer Instruction.
<!-- Tone: norsk ord? -->
Formativ vurdering er opptatt av å informere både underviseren og studenten
om hvor mye studentene forstår om et tema, og oppdage eventuelle misforståelser @boston2019Concept.
<!-- Tone: Strengt tatt er ikke formative vurdering “opptatt av å informere”.
Det blir bedre (på norsk) om du skriver:
«Formativ vurdering handler om at både underviseren og studenten
får tilbakemelding på studentenes forståelse og eventuelle misoppfatninger knyttet til et tema.» -->
Dette gjør det mulig å adressere misforståelser omgående,
noe som hjelper studenter til å komme videre gjennom materialet.
I motsetning til summativ vurdering (f. eks. eksamen) gis det ikke karakter ved formativ vurdering,
<!-- selv om noen ganger deltakelsen kan være et krav for å kunne bestå et kurs. -->
Ideelt sett kan formativ vurdering gjøres raskt og på en enkel måte
for studenter og lærere å delta og se resultatene.

Peer Instruction er en evidensbasert aktiv læringsmetode der studentene aktivt diskuterer materialet
basert på spørsmål levert av underviseren @mazur1997Peer.
Ved å be studentene om å reflektere over kursmateriell med sine egne ord,
er en student som nettopp forsto materialet i stand til å forklare det på en måte
som fungerer bedre for en student som nesten forstår materialet.
Metoden har vist positive resultater på studentens læring i programmering @crouch2001Peer.

I min undervisning bruker jeg 
<!-- formativ vurdering i kombinasjon med Peer Instruction, gjennom -->
flervalgsspørsmål som først besvares av alle studentene via Mentimeter
([ped.mappe @sec-vl-formvurd]).
Når den første runden av stemmingen viser uenighet, og dermed misforståelser
blant studentene, lar jeg dem studere svaralternativer seg i mellom.
Den neste avstemningen viser da oftest at flere har forstått det.

## En forskende tilnærming

Forskning handler mye om å prøve ut ting, og evaluere resultatene i lys av
tidligere forskning og teorier.
Som sagt er tar jeg samme utgangspunkt når jeg utformer undervisningsopplegg.
Som beskrevet over har jeg teste udnervisningsformer som
samkoding, og formativ vurdering med Peer Instruction.
Den viktigste måte å evaluere slike tiltak på er å be
deltakere, studenter og gruppelærere, om tilbakemelding.

På slutten av gruppetimene ber jeg studentene å besvare
en online ‘exit quiz’: "Hva var bra med dagens gruppetime?"
og "Hva er fortsatt uklart for deg?"
På slutten av oppgavene som studenter levere, og eksamen,
er det et frivillig spørsmål om egenvurdering
(hva mestrer du, og hva er fortsatt utfordrende).
Svarene på disse gir verdifull tilbakemelding
for å forstå eventuelle problemer studentene sitter med.
Noe av dette kan adresseres umiddelbart i neste gruppetime.

Resultatene av midtveisevaluering og en sluttevaluering ([ped.mappe @sec-vl-emneeval])
diskuteres med studentrepresentantene,
som vi har felles med de andre 1. semester kursene.
Evalueringer førte til at jeg lærte hvilke at flervalgsoppgaver fungerte veldig bra,
men ikke penn-og-papir oppgavene vi prøvde ut en periode,
utvikling av mengdetreningsoppgaver i programmering.
Vi har fortsatt en jobb å gjøre med øke relevans av forelesninger.

En annen effektiv og veldig givende (og hyggelig) måte å evaluere undervisning på
er å observere studentene mens de jobber med faget.
Det er vanskelig å sette av nok tid til det,
men jeg opplever alltig at jeg får mye innsikt i
hvordan studentene tenker, og deres misforståelser rundt stoffet.
For eksempel kan de lese en oppgavetekst på en hel annerledes måte
enn den var ment. 
Dette hjelper meg å forbedre kursmaterialet over tid.

<!-- Tone: HVordan har disse endringene forbedret studentenes læring?
Har evalueringene endret seg etter endringene? -->

Gruppelærere er de som er nærmest studentene
og bør dermed en viktig kilde til informasjon.
Jeg ber dem derfor å beskrive erfaringer umiddelbart etter undervisningen
i et delt online erfaringsdokument (Google Docs),
som diskuteres i felleskap på de ukentlige gruppelærermøtene.
Dette lar meg rette opp feil i materialet som skal gis igjen samme uke,
og er grunnlaget for forbedringer til neste gang.
Dette gir også gruppelærere eierskap i undervisningsutvikling,
noe de setter pris på.

En annen effektiv måte å får vurdert sin undervisning på er 
å be utenforstående personer 'forske' på sine studenter.
Spesielt de med pedagogisk-didaktisk kunnskap kan se på in undervisning
og komme med betraktninger forankret i læringsteori.

<!---
 Det er per dags dato lite forskningsbasert kunnskap om hvordan biologistudenter 
stiller seg til programmering i biologi og hvilke læringsstrategier de bruker.
Vi er derfor i en unik posisjon til å fremskaffe slik kunnskap
ved å ‘forske på’ studenter i BIOS1100. 
--->

Jeg har vært med i et tverrfaglig veilederteam for fire lektorstudenter
som har tatt en undervisningsrettet master der målet har vært
å undersøke BIOS1100-studenters holdninger til,
motivasjon for, og problemløsningsstrategier i 
programmering og modellering i biologi ([ped.mappe @sec-vl-forskning]).

Jeg har fra begynnelsen av tatt utgangspunkt i at problemstillinger vi jobber med
skal være relevant for biovitenskapstudenter.
Det var gledelig å finne ut at dette er støttet av tidligere forsking:
bruk av faglig relevante og autentiske eksempler bidrar til opplved 
nytteverdi, som gir ytre motivasjon @ryan2000Intrinsic,
og økt mestringsforventning @eccles2002Motivational.
Dette viser også relevans for resten av studieprogrammet, 
som kan bidra til økt interesse @hidi2006FourPhase.

Jeg mener nå også at samkoding som undervisningsform bidrar til mestringsfølelse,
noe som er viktig for engasjement @bandura1977Selfefficacy.

Funnene i masterprosjekter har jeg brukt aktivt for å forbedre kurset,
både faglig og hvordan emnet undervises.
Eksempler er økt relevans i valg av temaer som for eksempel modellering av Covid-19,
og økt fokus på problemløsningsstrategier.

<!-- Tone: Igjen, hvorfor tor du relevans er særlig viktig for å lære programmering i biologi?
Har du noen indikasjoner på at det støtter studentenes læring?
Enten støttet i litteratur eller egene erfaringer -->

Dette arbeidet har også blitt presentert på MNT konferansen og publisert
[NJSTEME: @gregers2019Lektorstudenter @eliassen2021Motivasjon].

<!--
Utfordring: hvordan å aktivisere studenter. Løsning: penn-og-papir øvelser, MCQ/Peer Instruction, Active Learning Classroom
Utfordring: kan ikke kode på eksamen. Løsning: eksamens-JupyterHub (constructive alignment)
Utfordring: studenter har ikke effektive problemløsningsstrategier. Løsning: CCSE sommerstudentprosjekt 2023?
Utfordring: gruppelærere har ikke pedagogisk kompetanse. Løsning: tilby enkel pedagogikk opplæring, så LA programmet
-->


## Kollegial holdning og praksis

Bør jeg ha med noe om Carpentries igjen her?

CCSE lederteam?

Flere innenfor og utenfor UiO er interessert i kurset BIOS1100
og bruk av Jupyter notebooks i undervisningen.
og jeg har holdt foredrag om det flere ganger ([ped.mappe @sec-vl-deling]). 
Jeg synes det er viktig å dele våre erfaringer slik at andre
kan dra nytte av det når de skal sette opp lignende kurs.

Siden 2022 leder jeg UndervisningsVerksted ved IBV, også kalt Underverk.
UnderVerk er "en workshopserie der alle som er involvert i undervisning ved
Institutt for Biovitenskap skal få mulighet til å arbeide med alle aspekter av
undervisning i et kollegialt fellesskap."
Kollega Tone Gregers ved IBV fikk i 2019 støtte fra MatNat fakultetets studiekvalitetsmidler
til å starte dette erfarinsdelingsinitiativet.
UnderVerk vi har organisert flere workshops, bl.a. om
Læringsmål og baklengsdesign, studentaktive læringsformer, digitale verktøy
([ped.mappe @sec-vl-underverk]).
UnderVerk er en veldig fin måte å gjennomføre erfaringsutveksling på,
og viser hvor mye gode undervisningsteknikker som brukes på instituttet,
og hvor lett det er å få dem fram og dele disse med hverandre.
UnderVerk sesjonene har økt kunnskap blant undervisere på IBV.
Som et konkret eksempel ble læringsutbyttebeskrivelser for kurset BIOS-IN5410 tilpasset
til å ha aktive verb [@biggs2011Teaching] etter en av sesjonene om hvordan man kan lage disse.

I store kurs overlates mye av undervisningen til gruppelærere.
Jeg synes da at det er opplagt at det tas grep for å hjelpe dem 
å bli gode undervisere, men dette er ikke en utbred praksis.

Jeg valgte derfor tidlig å
lære opp mine gruppelærere i noen enkle pedagogiske begreper og teknikker.
Her gjenbrukte jeg materialet fra The Carpentries instruktør trening.
Til min store glede ble det senere startet opp et Lærings Assistent program
ved fakultetet.
Jeg ba om, og fikk lov til å videreutvikle det og har vært involvert 
i Lærings-assistent-seminar som tilbys til ferske gruppelærere på MSc nivå
([ped.mappe @sec-vl-la]).
Nye gruppelærere i mine kurs sender jeg til dette programmet.
Jeg opplever at det å tilby noen enkel pedagogikk setter i gang en prosess
hos en gruppelærer som i seg selv, sammen med økt unnskap,
fører til at de blir seg mye mer bevisst rollen som underviser,
og at det gjør dem bedre i jobben sin.

Jeg er også blitt en del av undervisningssystemet for kurset
MNPED9000 – Teaching in STEM, som skal hjelpe PhD studenter med pliktarbeid
til å utvikle sin evne til fasilitere studentens læring
gjennom å utforske prinsipper for undervisning og læring i høyere utdanning.
([ped.mappe @sec-vl-mnped0000]).

<!---
 Et viktig aspekt av disse opplæringstilbudene er at undervisningsmetodene som undervises i
brukes aktivt under kurset: innholdet og aktivitetene kobles aktivt opp mot 
læringsutbyttebeskrivelser for å vise baklengs design av undervisningen
og meningsfylt samsvar i praksis;
øktene bruker aktive læringsaktiviteter som tenk-par-del, gruppediskusjoner,
studenter som gir tilbakemelding på hverandres arbeid. 
--->

Vår 2023 ble jeg bedt å lede prosjektet Digitalt Læringsmiljø 2030.
Prosjektet skulle undersøke hvordan UiO bruker det digitale læringsmiljøet
og muligheter for forbedring fremover.
Dette takket jeg gledelig ja til ([ped.mappe @sec-vl-dlm2030]).
Arbeidet ga meg en glimrende mulighet til å lære mye om hvordan undervisning
er organisert, og oppleves, på UiO
Jeg kunne bruke mine erfaringer, og påvirke veien videre for UiO
på denne viktige delen av undervisningen.
Prosjektteamet besto av ansatte fra den sentrale studieadministrasjonen,
LINK, og IT avdelingen var i prosjektgruppen,
og det var veldig interessant å høre akkurat deres perspektiver.
Prosjektet hadde veldig givende innspillsmøter
med studenter, undervisere, studieadministrative,og forskjellige fagavdelinger.
Undervisning er et samspill av mange aktører. 
Som underviser ser man ofte ikke de andre sidene av dette,
og arbeidet i prosjektet var veldig lærerikt fordi jeg fikk snakket med alle disse personene.
Jeg merket at mine erfaringer med undervisning kom til nytte da vi laget rapporten.
Anbefalinger i rapporten har med en del ting jeg brenner for:
at det digitale blir brukt på en pedagogisk måte @goodyear2015teaching,
bruk av relevant læringsteori for å støtte opp under anbefalinger,
redusere kompleksiteten i det digitale læringsmiljøet
(for å bergrense kognitiv belastning)
og et helhetsperspektiv der man ser på det digitale
som en del av et større, levende læringsmiljø.)
Jeg har selv lært mye om hvordan man kan lage 
et sammenhengende økosystem av undervisningsressurser
som studentene kan bruke av det de har behov for @luckin2008learner.
Vi er allerede i gang med å implementere en første versjon av det i BIOS1100,
med flere videofilmer, 'enkel forklart' tekster og test-deg-selv quizzer på Canvas.
Jeg håper og tror at rapporten kommer til å bidra med å gjøre 
det å gi og få undervisning til en bedre opplevelse for studenter og ansatte.

<!--- 
I 2021-2022 var jeg en del av
"Arbeidsgruppen for gjennomgang av ferdighetstrening i biovitenskapsprogrammet"
ved Institutt for Biovitenskap.
Arbeidsgruppen skulle gå gjennom bachelorprogrammet Biovitenskap,
med fokus på studentenes ferdighetstrening og samsvar mellom kurstilbudet
og læringsutbyttebeskrivelsen for programmet.
Det var veldig nyttig å snakke med flere kollegaer i arbeidsgruppen,
og med mange undervisere på workshoppene vi holdt,
reflektere over studieprogrammet,
og sammen komme med forslag til forbedring.
Arbeidsgruppen leverte en rapport ([ped.mappe @sec-vl-ag-ibv])
der det bl.a. be anbefalt opprettelsen av ‘studieløp’
for å synliggjøre muligheter for spesialisering og yrkesrelevans for programmet.
En annen anbefaling var å legge inn en feltkomponent i første semester,
og da i kurset BIOS1100.
Dette førte til at vi allerede i 2022 startet et prosjekt
for å pilotere denne feltkomponenten.
Høsten 2023 skal de første studentene ut i felt for å måle noen biologiske
egenskaper som de senere kan modellere i datalabben. 
--->

<!--
* Foredrag om CSE@IBV flere steder, inkludert UiB besøk ved STUT CircleU gruppen (online)
* Dialog med bl a Geir Kjetil om hvordan å undervise og vurdere programmering
* Nettverk Geir Kjetil programmering
* Rapport CSE@IBV fra 2019 (e.l.)
* OBiWoW (samarbeid med PhD studenter)
* erfaringsdokument BIOS1100 og MNPED9000
* CSE sommerstudenter og lektorstudenter
-->


En siste om Kugel @kugel1993professors
<!-- Tone: Dette er fint, men jeg hadde likt at du implementerte Kugel litt underveis.
Hvilket nivå var du på da du underviste 2x45 min
og hvor er du nå når du nå legger opp til et emne
der studentene selv finner ut hvilke læringsaktiviteter de trenger
å gjøre avhengig av behov og nivå? (som beskrevet i videre planer i avsittet om studentenes læring) -->


### Lederroller

<!-- Dokumenter eventuelle lederroller du har, eller har hatt, for å fremme utdanningskvalitet. -->

Jeg har, eller har hatt, følgende lederroller for å fremme utdanningskvalitet
([ped.mappe @sec-vl-leder])

* Leder, Prosjekt Digitalt Læringsmiljø 2030 (2023)
* Styreleder, Carpentry@UiO (2019-)
* Nestleder med ansvar for utdanning i Bioinformatikk,
Senter for Bioinformatikk (2018-)
* Medlem av ledergruppe Centre for Computing in Science Education
(CCSE, et SFU ved UiO) (2017-)
* Medlem Fagråd for IT i Utdanning (2022-)
* Leder for ​​Styret Forskerskole Digitalt Liv Norge (2016-2020)
* Medlem, så leder, Executive Council (styret) for The Carpentries (2018-2021)


### Videre planer

Framover ønsker jeg å forbedre den pedagogiske bruken av digitale verktøy i kurset,
spesielt Canvas. 
Det pågående prosjekt "Integrasjon av Jupyter og Canvas for digital vurdering"
som jeg har fått bevilget midler for, skal bidra til det,
og vi skal teste ut digitalt opplegg i Canvas som studentene skal gjennomføre
før undervisningen.

<!-- Beskriv og reflekter over konkrete planer for hvordan du vil jobbe med studentenes læring. -->

Jeg mener at Kunstig Intelligens verktøy
<!-- bytt ut med 'språkmodeller' ?-->
 verktøy som ChatGPT kan kunne brukes på en måte
som fremmer læring.
Dette skal vi begynne å undersøke i BIOS1100: hvordan kan studentene gå i dialog 
med en chatbot for å hjelpe dem å lære stoffet?
Jeg ser for meg at dette blir en del av et utvidet, sammenhengende økosystem av 
læringsressurser for studentene @luckin2008learner
hvor de kan velge det de trenger for å åppnå best læring.
<!-- Tone: Om mulig, skriv en innledende setning om hvordan språkmodeller
har gitt høyere utdanning utfordringer vi ikke har sett tidligere.
Vi må kanskje tenke helt nytt om både hva og hvordan vi underviser studentene
og hvordan vi vurderer.
Men brukt riktig og på en pedagogisk måte kan språkmodeller blir
et nyttig verktøry som fremmer læring.
Kanskje kan det du ønsker å teste ut skje i samarbeid med CCSE/KURT? -->

Jeg er veldig interessert i å utforske mulighetene som maskinlæring
og kunstig intelligens kan gi når det gjelder å analysere studentenes besvarelser.
For eksempel, kan vi bruke disse verktøyene til å finne ut
felles misforståelser studentene sitter med?

<!-- Tone: Hm, her er jeg litt usikker på hva du tenker?
Hva skal du med studentenes misforståelser?
Hva er målet med å hente disse dataene inn? -->


Rapporten av arbeidsgruppen som jobbet med gjennomgang av ferdighetstrening
i programmet og anbefalte å nedsette en egen arbeidsgruppe,
ledet av meg,
for å gjennomgå utviklingen av beregningskompetanse i bachelorprogrammet.
Jeg ønsker å starte opp dette arbeidet høsten 2023 eller våren 2024.

