# Vedlegg

## Fokus på studentenes læring

## En klar utvikling over tid

## En forskende tilnærming

### Emneevalueringer  {#sec-vl-emneeval}

* BIOS1100 (2017-)
  * Kurstittel: **Innføring i beregningsmodeller for biovitenskap**
  * Emnesider: <https://www.uio.no/studier/emner/matnat/ibv/BIOS1100/>
  * 2017
    * [Semestersidene](https://www.uio.no/studier/emner/matnat/ibv/BIOS1100/h17/ressurser/hovedside.md)
    * Fil: `Sluttrapport BIOS1100 Høsten 2017.pdf`

  * 2018
    * [Canvas sidene](https://uio.instructure.com/courses/5848)
    * Fil: `Sluttrapport BIOS1100 Høsten 2018.pdf`

  * 2019
    * [Canvas sidene](https://uio.instructure.com/courses/20058)
    * Fil: `Sluttrapport BIOS1100 Høsten 2019.pdf`

  * 2020
    * [Canvas sidene](https://uio.instructure.com/courses/26583)
    * Fil: `Sluttrapport BIOS1100 Høsten 2020.pdf`

  * Pensumbok "Introduction to Analysis and Modeling in Biology with Python", [siste versjon (august 2020)](https://uio.instructure.com/courses/26583/pages/introduction-to-analysis-and-modeling-in-biology-with-python?module_item_id=266340)
  * Jeg har skrevet noen blogposter om BIOS1100: <http://lexnederbragt.com/bios1100>


## Kollegial holdning og praksis

## Utdanningsfaglig CV

#### Universitetspedagogisk kompetanse

* *Felles innføringsdel* for Universitetspedagogisk Basiskompetanse i 2019
  * Kursbevis: Fil: `Kursbevis_universitetspedagogisk_basiskompetanse.pdf`
  * Utviklingsnotat: Fil: `Utviklingsnotat_Fellesdelen_2019.pdf`

* moduler tatt i tillegg til Fellesdelen:
  * Forskningsveiledning (2014)
    * Utviklingsarbeid: Fil: `Utviklingsarbeid_Forskningsveiledning_2014.pdf`
  * Forelesning og undervisning - det dramaturgiske aspekt (2015)
  * Pedagogisk mappe (2020)
  * Læring og undervisning med universell utforming (2022)
    * Innlevering: Fil: `Assignment_UU_2022.pdf`

* *Felles innføringsdel* i 2014 som 20% 1. amanuensis II
  * Utviklingsarbeid: Fil: `Utviklingsarbeid_Fellesdelen_2014.pdf`


----
Ikke plassert (ennå)

* Artikkel på mn.uio.no om hvordan det er å studere biovitenskap: https://www.uio.no/studier/program/biovitenskap/studiemiljo/hvordan-er-det-a-studere-biovitenskap.html.

